### ISSUE TITLE
有关获取embedding的问题

### ISSUE THREAD

**Issue by Fanb1ing** [WuNein/vllm4mteb#4]
你好！
非常感谢你的项目，完美解决了使用vllm部署llama获取embedding的问题，再次感谢！
我有一个小白问题想要请教，我使用vllm4emb.ipynb示例代码部署了llama3-8B-Insturction模型,获得的outputs = model.encode(docs)，这里encode返回的embedding是对应下图的哪个位置的embedding?
我发现使用原始llama3模型lora微调后获取的embedding并没有很大改变，我想debug原因是出在训练上还是出在获取embedding步骤上。
![image](https://github.com/user-attachments/assets/87ba38d2-7ba5-4c20-8271-7465388bf828)

祝假期愉快~

**Comment by WuNein** [comment]
> 我在外面玩😭

这个项目实际上是为这篇论文https://arxiv.org/abs/2307.16645 服务的。
取的是last hidden state 下一个词对应的位置的单一向量，具体请参考论文。

lora的问题我不是很确定vllm的实现是否和embedding兼容。建议你merge lora到llama上，我以往都是这么做的，然后载入merge的模型。

简单粗暴但是有效。

**Comment by Fanb1ing** [comment]
非常非常感谢快速回复！不好意思打扰你的旅行。
我去参考一下论文~ （lora我也是merge到llama后使用的，这一步应该没问题）

再次感谢！

**Comment by WuNein** [comment]
https://github.com/kongds/scaling_sentemb/blob/main/ft_llm.py

试试这个训练，非常清爽的代码（有点小绕）

**Comment by WuNein** [comment]
@Fanb1ing 你还有什么大的问题吗？没的话我想把issue关了？

**Comment by Fanb1ing** [comment]
没有问题了！已经完美解决，非常感谢~！
